FIND_PATH(OPENALSOFT_INCLUDE_DIR al.h
    HINTS
    $ENV{OPENALSOFTDIR}
    PATH_SUFFIXES AL include
    PATHS
)

FIND_LIBRARY(OPENALSOFT_LIBRARY 
    NAMES OpenAL al openal OpenAL32
    HINTS
    $ENV{OPENALSOFTDIR}
    PATH_SUFFIXES lib libs
    PATHS
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenALSoft DEFAULT_MSG OPENALSOFT_LIBRARY
    OPENALSOFT_INCLUDE_DIR)
MARK_AS_ADVANCED(OPENALSOFT_LIBRARY OPENALSOFT_INCLUDE_DIR)
