# Find glfw

IF(GLFW_INCLUDE_DIRS AND GLFW_LIBRARIES)
    set(GLFW_FIND_QUIETLY TRUE)
ENDIF(GLFW_INCLUDE_DIRS AND GLFW_LIBRARIES)

FIND_PATH(GLFW_INCLUDE_DIRS GLFW/glfw3.h)

SET(GLFW_NAMES ${GLFW_NAMES} libglfw3 glfw3)
FIND_LIBRARY(GLFW_LIBRARIES NAMES ${GLFW_NAMES} PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLFW DEFAULT_MSG GLFW_LIBRARIES GLFW_INCLUDE_DIRS)
mark_as_advanced(GLFW_INCLUDE_DIRS GLFW_LIBRARIES)