#include <string>
#include "keydef.h"
#include "stringcommon.h"

int translate_vk_to_key(int vk)
{
    switch (vk) {
        case 1: return SDL_BUTTON_LEFT;
        case 2: return SDL_BUTTON_RIGHT;
        case 4: return SDL_BUTTON_MIDDLE;
        case 5: return SDL_BUTTON_X1;
        case 6: return SDL_BUTTON_X2;
        case 8: return SDLK_BACKSPACE;
        case 9: return SDLK_TAB;
        case 12: return SDLK_CLEAR;
        case 13: return SDLK_RETURN;
        case 16: return SDLK_LSHIFT;
        case 17: return SDLK_LCTRL;
        case 18: return SDLK_RALT;
        case 19: return SDLK_PAUSE;
        case 20: return SDLK_CAPSLOCK;
        case 27: return SDLK_ESCAPE;
        case 32: return SDLK_SPACE;
        case 33: return SDLK_PAGEUP;
        case 34: return SDLK_PAGEDOWN;
        case 35: return SDLK_END;
        case 36: return SDLK_HOME;
        case 37: return SDLK_LEFT;
        case 38: return SDLK_UP;
        case 39: return SDLK_RIGHT;
        case 40: return SDLK_DOWN;
        case 45: return SDLK_INSERT;
        case 46: return SDLK_DELETE;
        case 48: return SDLK_0;
        case 49: return SDLK_1;
        case 50: return SDLK_2;
        case 51: return SDLK_3;
        case 52: return SDLK_4;
        case 53: return SDLK_5;
        case 54: return SDLK_6;
        case 55: return SDLK_7;
        case 56: return SDLK_8;
        case 57: return SDLK_9;
        case 65: return SDLK_a;
        case 66: return SDLK_b;
        case 67: return SDLK_c;
        case 68: return SDLK_d;
        case 69: return SDLK_e;
        case 70: return SDLK_f;
        case 71: return SDLK_g;
        case 72: return SDLK_h;
        case 73: return SDLK_i;
        case 74: return SDLK_j;
        case 75: return SDLK_k;
        case 76: return SDLK_l;
        case 77: return SDLK_m;
        case 78: return SDLK_n;
        case 79: return SDLK_o;
        case 80: return SDLK_p;
        case 81: return SDLK_q;
        case 82: return SDLK_r;
        case 83: return SDLK_s;
        case 84: return SDLK_t;
        case 85: return SDLK_u;
        case 86: return SDLK_v;
        case 87: return SDLK_w;
        case 88: return SDLK_x;
        case 89: return SDLK_y;
        case 90: return SDLK_z;
        case 91: return SDLK_LGUI;
        case 92: return SDLK_RGUI;
        case 93: return SDLK_MENU;
        case 96: return SDLK_KP_0;
        case 97: return SDLK_KP_1;
        case 98: return SDLK_KP_2;
        case 99: return SDLK_KP_3;
        case 100: return SDLK_KP_4;
        case 101: return SDLK_KP_5;
        case 102: return SDLK_KP_6;
        case 103: return SDLK_KP_7;
        case 104: return SDLK_KP_8;
        case 105: return SDLK_KP_9;
        case 106: return SDLK_KP_MULTIPLY;
        case 107: return SDLK_KP_PLUS;
        case 109: return SDLK_KP_MINUS;
        case 110: return SDLK_KP_DECIMAL;
        case 111: return SDLK_KP_DIVIDE;
        case 112: return SDLK_F1;
        case 113: return SDLK_F2;
        case 114: return SDLK_F3;
        case 115: return SDLK_F4;
        case 116: return SDLK_F5;
        case 117: return SDLK_F6;
        case 118: return SDLK_F7;
        case 119: return SDLK_F8;
        case 120: return SDLK_F9;
        case 121: return SDLK_F10;
        case 122: return SDLK_F11;
        case 123: return SDLK_F12;
        case 124: return SDLK_F13;
        case 125: return SDLK_F14;
        case 126: return SDLK_F15;
        case 127: return SDLK_F16;
        case 128: return SDLK_F17;
        case 129: return SDLK_F18;
        case 130: return SDLK_F19;
        case 131: return SDLK_F20;
        case 132: return SDLK_F21;
        case 133: return SDLK_F22;
        case 134: return SDLK_F23;
        case 135: return SDLK_F24;
        case 144: return SDLK_NUMLOCKCLEAR;
        case 145: return SDLK_SCROLLLOCK;
        case 160: return SDLK_LSHIFT;
        case 161: return SDLK_RSHIFT;
        case 162: return SDLK_LCTRL;
        case 163: return SDLK_RCTRL;
        case 164: return SDLK_LALT;
        case 165: return SDLK_RALT;
        case 186: return SDLK_SEMICOLON;
        case 187: return SDLK_EQUALS;
        case 188: return SDLK_COMMA;
        case 189: return SDLK_MINUS;
        case 190: return SDLK_PERIOD;
        case 191: return SDLK_SLASH;
        case 192: return SDLK_BACKQUOTE;
        case 219: return SDLK_LEFTBRACKET;
        case 220: return SDLK_BACKSLASH;
        case 221: return SDLK_RIGHTBRACKET;
        case 222: return SDLK_QUOTE;
        case 226: return SDLK_BACKSLASH;
    }
    return -1;
}

int translate_string_to_key(const std::string & in_name)
{
    std::string name = in_name;
    to_lower(name);
    if (name.compare(0, 10, "mouse left") == 0) return SDL_BUTTON_LEFT;
    if (name.compare(0, 11, "mouse right") == 0) return SDL_BUTTON_RIGHT;
    if (name.compare(0, 12, "mouse middle") == 0) return SDL_BUTTON_MIDDLE;
    if (name.compare(0, 8, "mouse x1") == 0) return SDL_BUTTON_X1;
    if (name.compare(0, 8, "mouse x2") == 0) return SDL_BUTTON_X2;
    if (name.compare(0, 9, "backspace") == 0) return SDLK_BACKSPACE;
    if (name.compare(0, 3, "tab") == 0) return SDLK_TAB;
    if (name.compare(0, 5, "clear") == 0) return SDLK_CLEAR;
    if (name.compare(0, 6, "return") == 0) return SDLK_RETURN;
    if (name.compare(0, 5, "shift") == 0) return SDLK_LSHIFT;
    if (name.compare(0, 7, "control") == 0) return SDLK_LCTRL;
    if (name.compare(0, 3, "alt") == 0) return SDLK_RALT;
    if (name.compare(0, 5, "break") == 0) return SDLK_PAUSE;
    if (name.compare(0, 8, "capslock") == 0) return SDLK_CAPSLOCK;
    if (name.compare(0, 6, "escape") == 0) return SDLK_ESCAPE;
    if (name.compare(0, 5, "space") == 0) return SDLK_SPACE;
    if (name.compare(0, 7, "page up") == 0) return SDLK_PAGEUP;
    if (name.compare(0, 9, "page down") == 0) return SDLK_PAGEDOWN;
    if (name.compare(0, 3, "end") == 0) return SDLK_END;
    if (name.compare(0, 4, "home") == 0) return SDLK_HOME;
    if (name.compare(0, 4, "left") == 0) return SDLK_LEFT;
    if (name.compare(0, 2, "up") == 0) return SDLK_UP;
    if (name.compare(0, 5, "right") == 0) return SDLK_RIGHT;
    if (name.compare(0, 4, "down") == 0) return SDLK_DOWN;
    if (name.compare(0, 6, "insert") == 0) return SDLK_INSERT;
    if (name.compare(0, 6, "delete") == 0) return SDLK_DELETE;
    if (name.compare(0, 1, "0") == 0) return SDLK_0;
    if (name.compare(0, 1, "1") == 0) return SDLK_1;
    if (name.compare(0, 1, "2") == 0) return SDLK_2;
    if (name.compare(0, 1, "3") == 0) return SDLK_3;
    if (name.compare(0, 1, "4") == 0) return SDLK_4;
    if (name.compare(0, 1, "5") == 0) return SDLK_5;
    if (name.compare(0, 1, "6") == 0) return SDLK_6;
    if (name.compare(0, 1, "7") == 0) return SDLK_7;
    if (name.compare(0, 1, "8") == 0) return SDLK_8;
    if (name.compare(0, 1, "9") == 0) return SDLK_9;
    if (name.compare(0, 1, "a") == 0) return SDLK_a;
    if (name.compare(0, 1, "b") == 0) return SDLK_b;
    if (name.compare(0, 1, "c") == 0) return SDLK_c;
    if (name.compare(0, 1, "d") == 0) return SDLK_d;
    if (name.compare(0, 1, "e") == 0) return SDLK_e;
    if (name.compare(0, 1, "f") == 0) return SDLK_f;
    if (name.compare(0, 1, "g") == 0) return SDLK_g;
    if (name.compare(0, 1, "h") == 0) return SDLK_h;
    if (name.compare(0, 1, "i") == 0) return SDLK_i;
    if (name.compare(0, 1, "j") == 0) return SDLK_j;
    if (name.compare(0, 1, "k") == 0) return SDLK_k;
    if (name.compare(0, 1, "l") == 0) return SDLK_l;
    if (name.compare(0, 1, "m") == 0) return SDLK_m;
    if (name.compare(0, 1, "n") == 0) return SDLK_n;
    if (name.compare(0, 1, "o") == 0) return SDLK_o;
    if (name.compare(0, 1, "p") == 0) return SDLK_p;
    if (name.compare(0, 1, "q") == 0) return SDLK_q;
    if (name.compare(0, 1, "r") == 0) return SDLK_r;
    if (name.compare(0, 1, "s") == 0) return SDLK_s;
    if (name.compare(0, 1, "t") == 0) return SDLK_t;
    if (name.compare(0, 1, "u") == 0) return SDLK_u;
    if (name.compare(0, 1, "v") == 0) return SDLK_v;
    if (name.compare(0, 1, "w") == 0) return SDLK_w;
    if (name.compare(0, 1, "x") == 0) return SDLK_x;
    if (name.compare(0, 1, "y") == 0) return SDLK_y;
    if (name.compare(0, 1, "z") == 0) return SDLK_z;
    if (name.compare(0, 11, "left window") == 0) return SDLK_LGUI;
    if (name.compare(0, 12, "right window") == 0) return SDLK_RGUI;
    if (name.compare(0, 4, "menu") == 0) return SDLK_MENU;
    if (name.compare(0, 9, "0 numeric") == 0) return SDLK_KP_0;
    if (name.compare(0, 9, "1 numeric") == 0) return SDLK_KP_1;
    if (name.compare(0, 9, "2 numeric") == 0) return SDLK_KP_2;
    if (name.compare(0, 9, "3 numeric") == 0) return SDLK_KP_3;
    if (name.compare(0, 9, "4 numeric") == 0) return SDLK_KP_4;
    if (name.compare(0, 9, "5 numeric") == 0) return SDLK_KP_5;
    if (name.compare(0, 9, "6 numeric") == 0) return SDLK_KP_6;
    if (name.compare(0, 9, "7 numeric") == 0) return SDLK_KP_7;
    if (name.compare(0, 9, "8 numeric") == 0) return SDLK_KP_8;
    if (name.compare(0, 9, "9 numeric") == 0) return SDLK_KP_9;
    if (name.compare(0, 1, "*") == 0) return SDLK_KP_MULTIPLY;
    if (name.compare(0, 1, "+") == 0) return SDLK_KP_PLUS;
    if (name.compare(0, 1, "-") == 0) return SDLK_KP_MINUS;
    if (name.compare(0, 7, "decimal") == 0) return SDLK_KP_DECIMAL;
    if (name.compare(0, 1, "/") == 0) return SDLK_KP_DIVIDE;
    if (name.compare(0, 2, "f1") == 0) return SDLK_F1;
    if (name.compare(0, 2, "f2") == 0) return SDLK_F2;
    if (name.compare(0, 2, "f3") == 0) return SDLK_F3;
    if (name.compare(0, 2, "f4") == 0) return SDLK_F4;
    if (name.compare(0, 2, "f5") == 0) return SDLK_F5;
    if (name.compare(0, 2, "f6") == 0) return SDLK_F6;
    if (name.compare(0, 2, "f7") == 0) return SDLK_F7;
    if (name.compare(0, 2, "f8") == 0) return SDLK_F8;
    if (name.compare(0, 2, "f9") == 0) return SDLK_F9;
    if (name.compare(0, 3, "f10") == 0) return SDLK_F10;
    if (name.compare(0, 3, "f11") == 0) return SDLK_F11;
    if (name.compare(0, 3, "f12") == 0) return SDLK_F12;
    if (name.compare(0, 3, "f13") == 0) return SDLK_F13;
    if (name.compare(0, 3, "f14") == 0) return SDLK_F14;
    if (name.compare(0, 3, "f15") == 0) return SDLK_F15;
    if (name.compare(0, 3, "f16") == 0) return SDLK_F16;
    if (name.compare(0, 3, "f17") == 0) return SDLK_F17;
    if (name.compare(0, 3, "f18") == 0) return SDLK_F18;
    if (name.compare(0, 3, "f19") == 0) return SDLK_F19;
    if (name.compare(0, 3, "f20") == 0) return SDLK_F20;
    if (name.compare(0, 3, "f21") == 0) return SDLK_F21;
    if (name.compare(0, 3, "f22") == 0) return SDLK_F22;
    if (name.compare(0, 3, "f23") == 0) return SDLK_F23;
    if (name.compare(0, 3, "f24") == 0) return SDLK_F24;
    if (name.compare(0, 7, "numlock") == 0) return SDLK_NUMLOCKCLEAR;
    if (name.compare(0, 9, "scrollock") == 0) return SDLK_SCROLLLOCK;
    if (name.compare(0, 10, "shift left") == 0) return SDLK_LSHIFT;
    if (name.compare(0, 11, "shift right") == 0) return SDLK_RSHIFT;
    if (name.compare(0, 12, "control left") == 0) return SDLK_LCTRL;
    if (name.compare(0, 13, "control right") == 0) return SDLK_RCTRL;
    if (name.compare(0, 8, "alt left") == 0) return SDLK_LALT;
    if (name.compare(0, 9, "alt right") == 0) return SDLK_RALT;
    return -1;
}

std::string translate_vk_to_string(int vk)
{
    switch (vk) {
        case 1: return std::string("Mouse Left", 10);
        case 2: return std::string("Mouse Right", 11);
        case 4: return std::string("Mouse Middle", 12);
        case 5: return std::string("Mouse X1", 8);
        case 6: return std::string("Mouse X2", 8);
        case 8: return std::string("Backspace", 9);
        case 9: return std::string("Tab", 3);
        case 12: return std::string("Clear", 5);
        case 13: return std::string("Return", 6);
        case 16: return std::string("Shift", 5);
        case 17: return std::string("Control", 7);
        case 18: return std::string("Alt", 3);
        case 19: return std::string("Break", 5);
        case 20: return std::string("Capslock", 8);
        case 27: return std::string("Escape", 6);
        case 32: return std::string("Space", 5);
        case 33: return std::string("Page up", 7);
        case 34: return std::string("Page down", 9);
        case 35: return std::string("End", 3);
        case 36: return std::string("Home", 4);
        case 37: return std::string("Left", 4);
        case 38: return std::string("Up", 2);
        case 39: return std::string("Right", 5);
        case 40: return std::string("Down", 4);
        case 45: return std::string("Insert", 6);
        case 46: return std::string("Delete", 6);
        case 48: return std::string("0", 1);
        case 49: return std::string("1", 1);
        case 50: return std::string("2", 1);
        case 51: return std::string("3", 1);
        case 52: return std::string("4", 1);
        case 53: return std::string("5", 1);
        case 54: return std::string("6", 1);
        case 55: return std::string("7", 1);
        case 56: return std::string("8", 1);
        case 57: return std::string("9", 1);
        case 65: return std::string("A", 1);
        case 66: return std::string("B", 1);
        case 67: return std::string("C", 1);
        case 68: return std::string("D", 1);
        case 69: return std::string("E", 1);
        case 70: return std::string("F", 1);
        case 71: return std::string("G", 1);
        case 72: return std::string("H", 1);
        case 73: return std::string("I", 1);
        case 74: return std::string("J", 1);
        case 75: return std::string("K", 1);
        case 76: return std::string("L", 1);
        case 77: return std::string("M", 1);
        case 78: return std::string("N", 1);
        case 79: return std::string("O", 1);
        case 80: return std::string("P", 1);
        case 81: return std::string("Q", 1);
        case 82: return std::string("R", 1);
        case 83: return std::string("S", 1);
        case 84: return std::string("T", 1);
        case 85: return std::string("U", 1);
        case 86: return std::string("V", 1);
        case 87: return std::string("W", 1);
        case 88: return std::string("X", 1);
        case 89: return std::string("Y", 1);
        case 90: return std::string("Z", 1);
        case 91: return std::string("Left Window", 11);
        case 92: return std::string("Right Window", 12);
        case 93: return std::string("Menu", 4);
        case 96: return std::string("0 numeric", 9);
        case 97: return std::string("1 numeric", 9);
        case 98: return std::string("2 numeric", 9);
        case 99: return std::string("3 numeric", 9);
        case 100: return std::string("4 numeric", 9);
        case 101: return std::string("5 numeric", 9);
        case 102: return std::string("6 numeric", 9);
        case 103: return std::string("7 numeric", 9);
        case 104: return std::string("8 numeric", 9);
        case 105: return std::string("9 numeric", 9);
        case 106: return std::string("*", 1);
        case 107: return std::string("+", 1);
        case 109: return std::string("-", 1);
        case 110: return std::string("Decimal", 7);
        case 111: return std::string("/", 1);
        case 112: return std::string("F1", 2);
        case 113: return std::string("F2", 2);
        case 114: return std::string("F3", 2);
        case 115: return std::string("F4", 2);
        case 116: return std::string("F5", 2);
        case 117: return std::string("F6", 2);
        case 118: return std::string("F7", 2);
        case 119: return std::string("F8", 2);
        case 120: return std::string("F9", 2);
        case 121: return std::string("F10", 3);
        case 122: return std::string("F11", 3);
        case 123: return std::string("F12", 3);
        case 124: return std::string("F13", 3);
        case 125: return std::string("F14", 3);
        case 126: return std::string("F15", 3);
        case 127: return std::string("F16", 3);
        case 128: return std::string("F17", 3);
        case 129: return std::string("F18", 3);
        case 130: return std::string("F19", 3);
        case 131: return std::string("F20", 3);
        case 132: return std::string("F21", 3);
        case 133: return std::string("F22", 3);
        case 134: return std::string("F23", 3);
        case 135: return std::string("F24", 3);
        case 144: return std::string("Numlock", 7);
        case 145: return std::string("Scrollock", 9);
        case 160: return std::string("Shift Left", 10);
        case 161: return std::string("Shift Right", 11);
        case 162: return std::string("Control Left", 12);
        case 163: return std::string("Control Right", 13);
        case 164: return std::string("Alt Left", 8);
        case 165: return std::string("Alt Right", 9);
    }
    return "";
}

std::string translate_key_to_string(int key)
{
    switch (key) {
        case SDLK_KP_MULTIPLY: return std::string("*", 1);
        case SDLK_CAPSLOCK: return std::string("Capslock", 8);
        case SDLK_DELETE: return std::string("Delete", 6);
        case SDLK_INSERT: return std::string("Insert", 6);
        case SDLK_UP: return std::string("Up", 2);
        case SDLK_b: return std::string("B", 1);
        case SDLK_RCTRL: return std::string("Control Right", 13);
        case SDL_BUTTON_MIDDLE: return std::string("Mouse Middle", 12);
        case SDLK_NUMLOCKCLEAR: return std::string("Numlock", 7);
        case SDL_BUTTON_X1: return std::string("Mouse X1", 8);
        case SDL_BUTTON_X2: return std::string("Mouse X2", 8);
        case SDLK_k: return std::string("K", 1);
        case SDLK_RGUI: return std::string("Right Window", 12);
        case SDLK_LGUI: return std::string("Left Window", 11);
        case SDLK_F24: return std::string("F24", 3);
        case SDLK_F23: return std::string("F23", 3);
        case SDLK_F22: return std::string("F22", 3);
        case SDLK_F21: return std::string("F21", 3);
        case SDLK_F20: return std::string("F20", 3);
        case SDLK_KP_8: return std::string("8 numeric", 9);
        case SDLK_KP_9: return std::string("9 numeric", 9);
        case SDLK_KP_4: return std::string("4 numeric", 9);
        case SDLK_KP_5: return std::string("5 numeric", 9);
        case SDLK_KP_6: return std::string("6 numeric", 9);
        case SDLK_KP_7: return std::string("7 numeric", 9);
        case SDLK_KP_0: return std::string("0 numeric", 9);
        case SDLK_KP_1: return std::string("1 numeric", 9);
        case SDLK_KP_2: return std::string("2 numeric", 9);
        case SDLK_KP_3: return std::string("3 numeric", 9);
        case SDLK_F12: return std::string("F12", 3);
        case SDLK_F13: return std::string("F13", 3);
        case SDLK_F10: return std::string("F10", 3);
        case SDLK_F11: return std::string("F11", 3);
        case SDLK_F16: return std::string("F16", 3);
        case SDLK_F17: return std::string("F17", 3);
        case SDLK_F14: return std::string("F14", 3);
        case SDLK_F15: return std::string("F15", 3);
        case SDLK_F18: return std::string("F18", 3);
        case SDLK_F19: return std::string("F19", 3);
        case SDLK_LCTRL: return std::string("Control Left", 12);
        case SDL_BUTTON_RIGHT: return std::string("Mouse Right", 11);
        case SDLK_RALT: return std::string("Alt Right", 9);
        case SDLK_RETURN: return std::string("Return", 6);
        case SDLK_PAUSE: return std::string("Break", 5);
        case SDLK_SCROLLLOCK: return std::string("Scrollock", 9);
        case SDLK_KP_ENTER: return std::string("Return", 6);
        case SDLK_ESCAPE: return std::string("Escape", 6);
        case SDLK_RSHIFT: return std::string("Shift Right", 11);
        case SDLK_KP_MINUS: return std::string("-", 1);
        case SDLK_KP_DECIMAL: return std::string("Decimal", 7);
        case SDLK_PAGEDOWN: return std::string("Page down", 9);
        case SDLK_PAGEUP: return std::string("Page up", 7);
        case SDL_BUTTON_LEFT: return std::string("Mouse Left", 10);
        case SDLK_0: return std::string("0", 1);
        case SDLK_KP_PLUS: return std::string("+", 1);
        case SDLK_END: return std::string("End", 3);
        case SDLK_TAB: return std::string("Tab", 3);
        case SDLK_HOME: return std::string("Home", 4);
        case SDLK_KP_DIVIDE: return std::string("/", 1);
        case SDLK_RIGHT: return std::string("Right", 5);
        case SDLK_DOWN: return std::string("Down", 4);
        case SDLK_u: return std::string("U", 1);
        case SDLK_t: return std::string("T", 1);
        case SDLK_w: return std::string("W", 1);
        case SDLK_v: return std::string("V", 1);
        case SDLK_q: return std::string("Q", 1);
        case SDLK_p: return std::string("P", 1);
        case SDLK_s: return std::string("S", 1);
        case SDLK_r: return std::string("R", 1);
        case SDLK_BACKSPACE: return std::string("Backspace", 9);
        case SDLK_y: return std::string("Y", 1);
        case SDLK_x: return std::string("X", 1);
        case SDLK_z: return std::string("Z", 1);
        case SDLK_e: return std::string("E", 1);
        case SDLK_d: return std::string("D", 1);
        case SDLK_g: return std::string("G", 1);
        case SDLK_f: return std::string("F", 1);
        case SDLK_a: return std::string("A", 1);
        case SDLK_c: return std::string("C", 1);
        case SDLK_LEFT: return std::string("Left", 4);
        case SDLK_m: return std::string("M", 1);
        case SDLK_l: return std::string("L", 1);
        case SDLK_o: return std::string("O", 1);
        case SDLK_n: return std::string("N", 1);
        case SDLK_i: return std::string("I", 1);
        case SDLK_h: return std::string("H", 1);
        case SDLK_LSHIFT: return std::string("Shift Left", 10);
        case SDLK_j: return std::string("J", 1);
        case SDLK_F8: return std::string("F8", 2);
        case SDLK_F9: return std::string("F9", 2);
        case SDLK_F1: return std::string("F1", 2);
        case SDLK_F2: return std::string("F2", 2);
        case SDLK_F3: return std::string("F3", 2);
        case SDLK_F4: return std::string("F4", 2);
        case SDLK_F5: return std::string("F5", 2);
        case SDLK_F6: return std::string("F6", 2);
        case SDLK_F7: return std::string("F7", 2);
        case SDLK_LALT: return std::string("Alt Left", 8);
        case SDLK_5: return std::string("5", 1);
        case SDLK_4: return std::string("4", 1);
        case SDLK_7: return std::string("7", 1);
        case SDLK_6: return std::string("6", 1);
        case SDLK_1: return std::string("1", 1);
        case SDLK_MENU: return std::string("Menu", 4);
        case SDLK_3: return std::string("3", 1);
        case SDLK_2: return std::string("2", 1);
        case SDLK_9: return std::string("9", 1);
        case SDLK_8: return std::string("8", 1);
        case SDLK_CLEAR: return std::string("Clear", 5);
        case SDLK_SPACE: return std::string("Space", 5);
    }
    return "";
}
