#define CHOWDREN_KEY_UNKNOWN            -1
#define CHOWDREN_KEY_SPACE              32
#define CHOWDREN_KEY_APOSTROPHE         39
#define CHOWDREN_KEY_COMMA              44
#define CHOWDREN_KEY_MINUS              45
#define CHOWDREN_KEY_PERIOD             46
#define CHOWDREN_KEY_SLASH              47
#define CHOWDREN_KEY_0                  48
#define CHOWDREN_KEY_1                  49
#define CHOWDREN_KEY_2                  50
#define CHOWDREN_KEY_3                  51
#define CHOWDREN_KEY_4                  52
#define CHOWDREN_KEY_5                  53
#define CHOWDREN_KEY_6                  54
#define CHOWDREN_KEY_7                  55
#define CHOWDREN_KEY_8                  56
#define CHOWDREN_KEY_9                  57
#define CHOWDREN_KEY_SEMICOLON          59
#define CHOWDREN_KEY_EQUAL              61
#define CHOWDREN_KEY_A                  65
#define CHOWDREN_KEY_B                  66
#define CHOWDREN_KEY_C                  67
#define CHOWDREN_KEY_D                  68
#define CHOWDREN_KEY_E                  69
#define CHOWDREN_KEY_F                  70
#define CHOWDREN_KEY_G                  71
#define CHOWDREN_KEY_H                  72
#define CHOWDREN_KEY_I                  73
#define CHOWDREN_KEY_J                  74
#define CHOWDREN_KEY_K                  75
#define CHOWDREN_KEY_L                  76
#define CHOWDREN_KEY_M                  77
#define CHOWDREN_KEY_N                  78
#define CHOWDREN_KEY_O                  79
#define CHOWDREN_KEY_P                  80
#define CHOWDREN_KEY_Q                  81
#define CHOWDREN_KEY_R                  82
#define CHOWDREN_KEY_S                  83
#define CHOWDREN_KEY_T                  84
#define CHOWDREN_KEY_U                  85
#define CHOWDREN_KEY_V                  86
#define CHOWDREN_KEY_W                  87
#define CHOWDREN_KEY_X                  88
#define CHOWDREN_KEY_Y                  89
#define CHOWDREN_KEY_Z                  90
#define CHOWDREN_KEY_LEFT_BRACKET       91
#define CHOWDREN_KEY_BACKSLASH          92
#define CHOWDREN_KEY_RIGHT_BRACKET      93
#define CHOWDREN_KEY_GRAVE_ACCENT       96
#define CHOWDREN_KEY_WORLD_1            161
#define CHOWDREN_KEY_WORLD_2            162
#define CHOWDREN_KEY_ESCAPE             256
#define CHOWDREN_KEY_ENTER              257
#define CHOWDREN_KEY_TAB                258
#define CHOWDREN_KEY_BACKSPACE          259
#define CHOWDREN_KEY_INSERT             260
#define CHOWDREN_KEY_DELETE             261
#define CHOWDREN_KEY_RIGHT              262
#define CHOWDREN_KEY_LEFT               263
#define CHOWDREN_KEY_DOWN               264
#define CHOWDREN_KEY_UP                 265
#define CHOWDREN_KEY_PAGE_UP            266
#define CHOWDREN_KEY_PAGE_DOWN          267
#define CHOWDREN_KEY_HOME               268
#define CHOWDREN_KEY_END                269
#define CHOWDREN_KEY_CAPS_LOCK          280
#define CHOWDREN_KEY_SCROLL_LOCK        281
#define CHOWDREN_KEY_NUM_LOCK           282
#define CHOWDREN_KEY_PRINT_SCREEN       283
#define CHOWDREN_KEY_PAUSE              284
#define CHOWDREN_KEY_F1                 290
#define CHOWDREN_KEY_F2                 291
#define CHOWDREN_KEY_F3                 292
#define CHOWDREN_KEY_F4                 293
#define CHOWDREN_KEY_F5                 294
#define CHOWDREN_KEY_F6                 295
#define CHOWDREN_KEY_F7                 296
#define CHOWDREN_KEY_F8                 297
#define CHOWDREN_KEY_F9                 298
#define CHOWDREN_KEY_F10                299
#define CHOWDREN_KEY_F11                300
#define CHOWDREN_KEY_F12                301
#define CHOWDREN_KEY_F13                302
#define CHOWDREN_KEY_F14                303
#define CHOWDREN_KEY_F15                304
#define CHOWDREN_KEY_F16                305
#define CHOWDREN_KEY_F17                306
#define CHOWDREN_KEY_F18                307
#define CHOWDREN_KEY_F19                308
#define CHOWDREN_KEY_F20                309
#define CHOWDREN_KEY_F21                310
#define CHOWDREN_KEY_F22                311
#define CHOWDREN_KEY_F23                312
#define CHOWDREN_KEY_F24                313
#define CHOWDREN_KEY_F25                314
#define CHOWDREN_KEY_KP_0               320
#define CHOWDREN_KEY_KP_1               321
#define CHOWDREN_KEY_KP_2               322
#define CHOWDREN_KEY_KP_3               323
#define CHOWDREN_KEY_KP_4               324
#define CHOWDREN_KEY_KP_5               325
#define CHOWDREN_KEY_KP_6               326
#define CHOWDREN_KEY_KP_7               327
#define CHOWDREN_KEY_KP_8               328
#define CHOWDREN_KEY_KP_9               329
#define CHOWDREN_KEY_KP_DECIMAL         330
#define CHOWDREN_KEY_KP_DIVIDE          331
#define CHOWDREN_KEY_KP_MULTIPLY        332
#define CHOWDREN_KEY_KP_SUBTRACT        333
#define CHOWDREN_KEY_KP_ADD             334
#define CHOWDREN_KEY_KP_ENTER           335
#define CHOWDREN_KEY_KP_EQUAL           336
#define CHOWDREN_KEY_LEFT_SHIFT         340
#define CHOWDREN_KEY_LEFT_CONTROL       341
#define CHOWDREN_KEY_LEFT_ALT           342
#define CHOWDREN_KEY_LEFT_SUPER         343
#define CHOWDREN_KEY_RIGHT_SHIFT        344
#define CHOWDREN_KEY_RIGHT_CONTROL      345
#define CHOWDREN_KEY_RIGHT_ALT          346
#define CHOWDREN_KEY_RIGHT_SUPER        347
#define CHOWDREN_KEY_MENU               348
#define CHOWDREN_KEY_LAST               CHOWDREN_KEY_MENU
#define CHOWDREN_MOD_SHIFT              0x0001
#define CHOWDREN_MOD_CONTROL            0x0002
#define CHOWDREN_MOD_ALT                0x0004
#define CHOWDREN_MOD_SUPER              0x0008
#define CHOWDREN_MOUSE_BUTTON_1         0
#define CHOWDREN_MOUSE_BUTTON_2         1
#define CHOWDREN_MOUSE_BUTTON_3         2
#define CHOWDREN_MOUSE_BUTTON_4         3
#define CHOWDREN_MOUSE_BUTTON_5         4
#define CHOWDREN_MOUSE_BUTTON_6         5
#define CHOWDREN_MOUSE_BUTTON_7         6
#define CHOWDREN_MOUSE_BUTTON_8         7
#define CHOWDREN_MOUSE_BUTTON_LAST      CHOWDREN_MOUSE_BUTTON_8
#define CHOWDREN_MOUSE_BUTTON_LEFT      CHOWDREN_MOUSE_BUTTON_1
#define CHOWDREN_MOUSE_BUTTON_RIGHT     CHOWDREN_MOUSE_BUTTON_2
#define CHOWDREN_MOUSE_BUTTON_MIDDLE    CHOWDREN_MOUSE_BUTTON_3
